<?php defined('SYSPATH') OR die('No direct access allowed.');
// ABC Start
$config['Ciara'] = "store/stores_home_page/Ciara";
$config['Ciara/products.html'] = "/store/product_list/Ciara";
$config['Ciara/today-deals.html'] = "/store/deal_list/Ciara";
$config['Ciara/auction.html'] = "/store/auction_list/Ciara";
$config['Ciara/products/c/(.*)/(.*).html'] = "/store/product_list/Ciara/$1/$2";
$config['Ciara/deal/c/(.*)/(.*).html'] = "/store/deal_list/Ciara/$1/$2";
$config['Ciara/auction/c/(.*)/(.*).html'] = "/store/auction_list/Ciara/$1/$2";
// ABC End
// MUSTY-SUB Start
$config['E-Store'] = "store/stores_home_page/E-Store";
$config['E-Store/products.html'] = "/store/product_list/E-Store";
$config['E-Store/today-deals.html'] = "/store/deal_list/E-Store";
$config['E-Store/auction.html'] = "/store/auction_list/E-Store";
$config['E-Store/products/c/(.*)/(.*).html'] = "/store/product_list/E-Store/$1/$2";
$config['E-Store/deal/c/(.*)/(.*).html'] = "/store/deal_list/E-Store/$1/$2";
$config['E-Store/auction/c/(.*)/(.*).html'] = "/store/auction_list/E-Store/$1/$2";
// MUSTY-SUB End



// MUSTY-SUB-2 Start
$config['MUSTY-SUB-2'] = "store/stores_home_page/MUSTY-SUB-2";
$config['MUSTY-SUB-2/products.html'] = "/store/product_list/MUSTY-SUB-2";
$config['MUSTY-SUB-2/today-deals.html'] = "/store/deal_list/MUSTY-SUB-2";
$config['MUSTY-SUB-2/auction.html'] = "/store/auction_list/MUSTY-SUB-2";
$config['MUSTY-SUB-2/products/c/(.*)/(.*).html'] = "/store/product_list/MUSTY-SUB-2/$1/$2";
$config['MUSTY-SUB-2/deal/c/(.*)/(.*).html'] = "/store/deal_list/MUSTY-SUB-2/$1/$2";
$config['MUSTY-SUB-2/auction/c/(.*)/(.*).html'] = "/store/auction_list/MUSTY-SUB-2/$1/$2";
// MUSTY-SUB-2 End
// ABC-Pvt-Ltd Start
$config['ABC-Pvt-Ltd'] = "store/stores_home_page/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/products.html'] = "/store/product_list/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/today-deals.html'] = "/store/deal_list/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/auction.html'] = "/store/auction_list/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/products/c/(.*)/(.*).html'] = "/store/product_list/ABC-Pvt-Ltd/$1/$2";
$config['ABC-Pvt-Ltd/deal/c/(.*)/(.*).html'] = "/store/deal_list/ABC-Pvt-Ltd/$1/$2";
$config['ABC-Pvt-Ltd/auction/c/(.*)/(.*).html'] = "/store/auction_list/ABC-Pvt-Ltd/$1/$2";
// ABC-Pvt-Ltd End
// MUSTY-MUSTY Start
$config['MUSTY-MUSTY'] = "store/stores_home_page/MUSTY-MUSTY";
$config['MUSTY-MUSTY/products.html'] = "/store/product_list/MUSTY-MUSTY";
$config['MUSTY-MUSTY/today-deals.html'] = "/store/deal_list/MUSTY-MUSTY";
$config['MUSTY-MUSTY/auction.html'] = "/store/auction_list/MUSTY-MUSTY";
$config['MUSTY-MUSTY/products/c/(.*)/(.*).html'] = "/store/product_list/MUSTY-MUSTY/$1/$2";
$config['MUSTY-MUSTY/deal/c/(.*)/(.*).html'] = "/store/deal_list/MUSTY-MUSTY/$1/$2";
$config['MUSTY-MUSTY/auction/c/(.*)/(.*).html'] = "/store/auction_list/MUSTY-MUSTY/$1/$2";
// MUSTY-MUSTY End
// Lispa Start
$config['Lispa'] = "store/stores_home_page/Lispa";
$config['Lispa/products.html'] = "/store/product_list/Lispa";
$config['Lispa/today-deals.html'] = "/store/deal_list/Lispa";
$config['Lispa/auction.html'] = "/store/auction_list/Lispa";
$config['Lispa/products/c/(.*)/(.*).html'] = "/store/product_list/Lispa/$1/$2";
$config['Lispa/deal/c/(.*)/(.*).html'] = "/store/deal_list/Lispa/$1/$2";
$config['Lispa/auction/c/(.*)/(.*).html'] = "/store/auction_list/Lispa/$1/$2";
// Lispa End
// Lispa2 Start
$config['Lispa2'] = "store/stores_home_page/Lispa2";
$config['Lispa2/products.html'] = "/store/product_list/Lispa2";
$config['Lispa2/today-deals.html'] = "/store/deal_list/Lispa2";
$config['Lispa2/auction.html'] = "/store/auction_list/Lispa2";
$config['Lispa2/products/c/(.*)/(.*).html'] = "/store/product_list/Lispa2/$1/$2";
$config['Lispa2/deal/c/(.*)/(.*).html'] = "/store/deal_list/Lispa2/$1/$2";
$config['Lispa2/auction/c/(.*)/(.*).html'] = "/store/auction_list/Lispa2/$1/$2";
// Lispa2 End
// AllStories Start
$config['AllStories'] = "store/stores_home_page/AllStories";
$config['AllStories/products.html'] = "/store/product_list/AllStories";
$config['AllStories/today-deals.html'] = "/store/deal_list/AllStories";
$config['AllStories/auction.html'] = "/store/auction_list/AllStories";
$config['AllStories/products/c/(.*)/(.*).html'] = "/store/product_list/AllStories/$1/$2";
$config['AllStories/deal/c/(.*)/(.*).html'] = "/store/deal_list/AllStories/$1/$2";
$config['AllStories/auction/c/(.*)/(.*).html'] = "/store/auction_list/AllStories/$1/$2";
// AllStories End
// Storesall Start
$config['Storesall'] = "store/stores_home_page/Storesall";
$config['Storesall/products.html'] = "/store/product_list/Storesall";
$config['Storesall/today-deals.html'] = "/store/deal_list/Storesall";
$config['Storesall/auction.html'] = "/store/auction_list/Storesall";
$config['Storesall/products/c/(.*)/(.*).html'] = "/store/product_list/Storesall/$1/$2";
$config['Storesall/deal/c/(.*)/(.*).html'] = "/store/deal_list/Storesall/$1/$2";
$config['Storesall/auction/c/(.*)/(.*).html'] = "/store/auction_list/Storesall/$1/$2";
// Storesall End
// AllStores Start
$config['AllStores'] = "store/stores_home_page/AllStores";
$config['AllStores/products.html'] = "/store/product_list/AllStores";
$config['AllStores/today-deals.html'] = "/store/deal_list/AllStores";
$config['AllStores/auction.html'] = "/store/auction_list/AllStores";
$config['AllStores/products/c/(.*)/(.*).html'] = "/store/product_list/AllStores/$1/$2";
$config['AllStores/deal/c/(.*)/(.*).html'] = "/store/deal_list/AllStores/$1/$2";
$config['AllStores/auction/c/(.*)/(.*).html'] = "/store/auction_list/AllStores/$1/$2";
// AllStores End
// gleexxx Start
$config['gleexxx'] = "store/stores_home_page/gleexxx";
$config['gleexxx/products.html'] = "/store/product_list/gleexxx";
$config['gleexxx/today-deals.html'] = "/store/deal_list/gleexxx";
$config['gleexxx/auction.html'] = "/store/auction_list/gleexxx";
$config['gleexxx/products/c/(.*)/(.*).html'] = "/store/product_list/gleexxx/$1/$2";
$config['gleexxx/deal/c/(.*)/(.*).html'] = "/store/deal_list/gleexxx/$1/$2";
$config['gleexxx/auction/c/(.*)/(.*).html'] = "/store/auction_list/gleexxx/$1/$2";
// gleexxx End
// xxlispa Start
$config['xxlispa'] = "store/stores_home_page/xxlispa";
$config['xxlispa/products.html'] = "/store/product_list/xxlispa";
$config['xxlispa/today-deals.html'] = "/store/deal_list/xxlispa";
$config['xxlispa/auction.html'] = "/store/auction_list/xxlispa";
$config['xxlispa/products/c/(.*)/(.*).html'] = "/store/product_list/xxlispa/$1/$2";
$config['xxlispa/deal/c/(.*)/(.*).html'] = "/store/deal_list/xxlispa/$1/$2";
$config['xxlispa/auction/c/(.*)/(.*).html'] = "/store/auction_list/xxlispa/$1/$2";
// xxlispa End
// pxshops Start
$config['pxshops'] = "store/stores_home_page/pxshops";
$config['pxshops/products.html'] = "/store/product_list/pxshops";
$config['pxshops/today-deals.html'] = "/store/deal_list/pxshops";
$config['pxshops/auction.html'] = "/store/auction_list/pxshops";
$config['pxshops/products/c/(.*)/(.*).html'] = "/store/product_list/pxshops/$1/$2";
$config['pxshops/deal/c/(.*)/(.*).html'] = "/store/deal_list/pxshops/$1/$2";
$config['pxshops/auction/c/(.*)/(.*).html'] = "/store/auction_list/pxshops/$1/$2";
// pxshops End
// GMLispa Start
$config['GMLispa'] = "store/stores_home_page/GMLispa";
$config['GMLispa/products.html'] = "/store/product_list/GMLispa";
$config['GMLispa/today-deals.html'] = "/store/deal_list/GMLispa";
$config['GMLispa/auction.html'] = "/store/auction_list/GMLispa";
$config['GMLispa/products/c/(.*)/(.*).html'] = "/store/product_list/GMLispa/$1/$2";
$config['GMLispa/deal/c/(.*)/(.*).html'] = "/store/deal_list/GMLispa/$1/$2";
$config['GMLispa/auction/c/(.*)/(.*).html'] = "/store/auction_list/GMLispa/$1/$2";
// GMLispa End
// lispaxxxx Start
$config['lispaxxxx'] = "store/stores_home_page/lispaxxxx";
$config['lispaxxxx/products.html'] = "/store/product_list/lispaxxxx";
$config['lispaxxxx/today-deals.html'] = "/store/deal_list/lispaxxxx";
$config['lispaxxxx/auction.html'] = "/store/auction_list/lispaxxxx";
$config['lispaxxxx/products/c/(.*)/(.*).html'] = "/store/product_list/lispaxxxx/$1/$2";
$config['lispaxxxx/deal/c/(.*)/(.*).html'] = "/store/deal_list/lispaxxxx/$1/$2";
$config['lispaxxxx/auction/c/(.*)/(.*).html'] = "/store/auction_list/lispaxxxx/$1/$2";
// lispaxxxx End
// lissxxp Start
$config['lissxxp'] = "store/stores_home_page/lissxxp";
$config['lissxxp/products.html'] = "/store/product_list/lissxxp";
$config['lissxxp/today-deals.html'] = "/store/deal_list/lissxxp";
$config['lissxxp/auction.html'] = "/store/auction_list/lissxxp";
$config['lissxxp/products/c/(.*)/(.*).html'] = "/store/product_list/lissxxp/$1/$2";
$config['lissxxp/deal/c/(.*)/(.*).html'] = "/store/deal_list/lissxxp/$1/$2";
$config['lissxxp/auction/c/(.*)/(.*).html'] = "/store/auction_list/lissxxp/$1/$2";
// lissxxp End
// Goodies Start
$config['Goodies'] = "store/stores_home_page/Goodies";
$config['Goodies/products.html'] = "/store/product_list/Goodies";
$config['Goodies/today-deals.html'] = "/store/deal_list/Goodies";
$config['Goodies/auction.html'] = "/store/auction_list/Goodies";
$config['Goodies/products/c/(.*)/(.*).html'] = "/store/product_list/Goodies/$1/$2";
$config['Goodies/deal/c/(.*)/(.*).html'] = "/store/deal_list/Goodies/$1/$2";
$config['Goodies/auction/c/(.*)/(.*).html'] = "/store/auction_list/Goodies/$1/$2";
// Goodies End
// lisxxqqkkj Start
$config['lisxxqqkkj'] = "store/stores_home_page/lisxxqqkkj";
$config['lisxxqqkkj/products.html'] = "/store/product_list/lisxxqqkkj";
$config['lisxxqqkkj/today-deals.html'] = "/store/deal_list/lisxxqqkkj";
$config['lisxxqqkkj/auction.html'] = "/store/auction_list/lisxxqqkkj";
$config['lisxxqqkkj/products/c/(.*)/(.*).html'] = "/store/product_list/lisxxqqkkj/$1/$2";
$config['lisxxqqkkj/deal/c/(.*)/(.*).html'] = "/store/deal_list/lisxxqqkkj/$1/$2";
$config['lisxxqqkkj/auction/c/(.*)/(.*).html'] = "/store/auction_list/lisxxqqkkj/$1/$2";
// lisxxqqkkj End
// uga Start
$config['uga'] = "store/stores_home_page/uga";
$config['uga/products.html'] = "/store/product_list/uga";
$config['uga/today-deals.html'] = "/store/deal_list/uga";
$config['uga/auction.html'] = "/store/auction_list/uga";
$config['uga/products/c/(.*)/(.*).html'] = "/store/product_list/uga/$1/$2";
$config['uga/deal/c/(.*)/(.*).html'] = "/store/deal_list/uga/$1/$2";
$config['uga/auction/c/(.*)/(.*).html'] = "/store/auction_list/uga/$1/$2";
// uga End
