<?php defined('SYSPATH') OR die('No direct access allowed.');
// ABC Start
$config['Ciara'] = "store/stores_home_page/Ciara";
$config['Ciara/products.html'] = "/store/product_list/Ciara";
$config['Ciara/today-deals.html'] = "/store/deal_list/Ciara";
$config['Ciara/auction.html'] = "/store/auction_list/Ciara";
$config['Ciara/products/c/(.*)/(.*).html'] = "/store/product_list/Ciara/$1/$2";
$config['Ciara/deal/c/(.*)/(.*).html'] = "/store/deal_list/Ciara/$1/$2";
$config['Ciara/auction/c/(.*)/(.*).html'] = "/store/auction_list/Ciara/$1/$2";
// ABC End
// MUSTY-SUB Start
$config['Blingworld'] = "store/stores_home_page/Blingworld";
$config['Blingworld/products.html'] = "/store/product_list/Blingworld";
$config['Blingworld/today-deals.html'] = "/store/deal_list/Blingworld";
$config['Blingworld/auction.html'] = "/store/auction_list/Blingworld";
$config['Blingworld/products/c/(.*)/(.*).html'] = "/store/product_list/Blingworld/$1/$2";
$config['Blingworld/deal/c/(.*)/(.*).html'] = "/store/deal_list/Blingworld/$1/$2";
$config['Blingworld/auction/c/(.*)/(.*).html'] = "/store/auction_list/Blingworld/$1/$2";
// MUSTY-SUB End
// MUSTY-SUB-2 Start
$config['MUSTY-SUB-2'] = "store/stores_home_page/MUSTY-SUB-2";
$config['MUSTY-SUB-2/products.html'] = "/store/product_list/MUSTY-SUB-2";
$config['MUSTY-SUB-2/today-deals.html'] = "/store/deal_list/MUSTY-SUB-2";
$config['MUSTY-SUB-2/auction.html'] = "/store/auction_list/MUSTY-SUB-2";
$config['MUSTY-SUB-2/products/c/(.*)/(.*).html'] = "/store/product_list/MUSTY-SUB-2/$1/$2";
$config['MUSTY-SUB-2/deal/c/(.*)/(.*).html'] = "/store/deal_list/MUSTY-SUB-2/$1/$2";
$config['MUSTY-SUB-2/auction/c/(.*)/(.*).html'] = "/store/auction_list/MUSTY-SUB-2/$1/$2";
// MUSTY-SUB-2 End
// ABC-Pvt-Ltd Start
$config['ABC-Pvt-Ltd'] = "store/stores_home_page/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/products.html'] = "/store/product_list/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/today-deals.html'] = "/store/deal_list/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/auction.html'] = "/store/auction_list/ABC-Pvt-Ltd";
$config['ABC-Pvt-Ltd/products/c/(.*)/(.*).html'] = "/store/product_list/ABC-Pvt-Ltd/$1/$2";
$config['ABC-Pvt-Ltd/deal/c/(.*)/(.*).html'] = "/store/deal_list/ABC-Pvt-Ltd/$1/$2";
$config['ABC-Pvt-Ltd/auction/c/(.*)/(.*).html'] = "/store/auction_list/ABC-Pvt-Ltd/$1/$2";
// ABC-Pvt-Ltd End
// MUSTY-MUSTY Start
$config['MUSTY-MUSTY'] = "store/stores_home_page/MUSTY-MUSTY";
$config['MUSTY-MUSTY/products.html'] = "/store/product_list/MUSTY-MUSTY";
$config['MUSTY-MUSTY/today-deals.html'] = "/store/deal_list/MUSTY-MUSTY";
$config['MUSTY-MUSTY/auction.html'] = "/store/auction_list/MUSTY-MUSTY";
$config['MUSTY-MUSTY/products/c/(.*)/(.*).html'] = "/store/product_list/MUSTY-MUSTY/$1/$2";
$config['MUSTY-MUSTY/deal/c/(.*)/(.*).html'] = "/store/deal_list/MUSTY-MUSTY/$1/$2";
$config['MUSTY-MUSTY/auction/c/(.*)/(.*).html'] = "/store/auction_list/MUSTY-MUSTY/$1/$2";
// MUSTY-MUSTY End
// Lispa Start
$config['Lispa'] = "store/stores_home_page/Lispa";
$config['Lispa/products.html'] = "/store/product_list/Lispa";
$config['Lispa/today-deals.html'] = "/store/deal_list/Lispa";
$config['Lispa/auction.html'] = "/store/auction_list/Lispa";
$config['Lispa/products/c/(.*)/(.*).html'] = "/store/product_list/Lispa/$1/$2";
$config['Lispa/deal/c/(.*)/(.*).html'] = "/store/deal_list/Lispa/$1/$2";
$config['Lispa/auction/c/(.*)/(.*).html'] = "/store/auction_list/Lispa/$1/$2";
// Lispa End
// Lispa2 Start
$config['Lispa2'] = "store/stores_home_page/Lispa2";
$config['Lispa2/products.html'] = "/store/product_list/Lispa2";
$config['Lispa2/today-deals.html'] = "/store/deal_list/Lispa2";
$config['Lispa2/auction.html'] = "/store/auction_list/Lispa2";
$config['Lispa2/products/c/(.*)/(.*).html'] = "/store/product_list/Lispa2/$1/$2";
$config['Lispa2/deal/c/(.*)/(.*).html'] = "/store/deal_list/Lispa2/$1/$2";
$config['Lispa2/auction/c/(.*)/(.*).html'] = "/store/auction_list/Lispa2/$1/$2";
// Lispa2 End
// AllStories Start
$config['AllStories'] = "store/stores_home_page/AllStories";
$config['AllStories/products.html'] = "/store/product_list/AllStories";
$config['AllStories/today-deals.html'] = "/store/deal_list/AllStories";
$config['AllStories/auction.html'] = "/store/auction_list/AllStories";
$config['AllStories/products/c/(.*)/(.*).html'] = "/store/product_list/AllStories/$1/$2";
$config['AllStories/deal/c/(.*)/(.*).html'] = "/store/deal_list/AllStories/$1/$2";
$config['AllStories/auction/c/(.*)/(.*).html'] = "/store/auction_list/AllStories/$1/$2";
// AllStories End
// Storesall Start
$config['Storesall'] = "store/stores_home_page/Storesall";
$config['Storesall/products.html'] = "/store/product_list/Storesall";
$config['Storesall/today-deals.html'] = "/store/deal_list/Storesall";
$config['Storesall/auction.html'] = "/store/auction_list/Storesall";
$config['Storesall/products/c/(.*)/(.*).html'] = "/store/product_list/Storesall/$1/$2";
$config['Storesall/deal/c/(.*)/(.*).html'] = "/store/deal_list/Storesall/$1/$2";
$config['Storesall/auction/c/(.*)/(.*).html'] = "/store/auction_list/Storesall/$1/$2";
// Storesall End
// AllStores Start
$config['AllStores'] = "store/stores_home_page/AllStores";
$config['AllStores/products.html'] = "/store/product_list/AllStores";
$config['AllStores/today-deals.html'] = "/store/deal_list/AllStores";
$config['AllStores/auction.html'] = "/store/auction_list/AllStores";
$config['AllStores/products/c/(.*)/(.*).html'] = "/store/product_list/AllStores/$1/$2";
$config['AllStores/deal/c/(.*)/(.*).html'] = "/store/deal_list/AllStores/$1/$2";
$config['AllStores/auction/c/(.*)/(.*).html'] = "/store/auction_list/AllStores/$1/$2";
// AllStores End
